version: 2
updates:      
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
