## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Spring Boot framework with MySQL Database Service"
stackDescription: Deploy Spring Boot framework with MySQL Database Service
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - compartment_ocid
  - compartment_SZ_ocid
  - tenancy_ocid
  - region

- title: Required Configuration
  visible: true  
  variables:
  - BastionInstanceShape
  - WebserverInstanceShape
  - mysql_db_system_admin_password 

- title: Optional Configuration
  visible: true  
  variables:
  - instance_os
  - linux_os_version
  - igw_display_name
  - vcn01_display_name
  - vcn01_dns_label
  - vcn01_cidr_block
  - vcn01_subnet_pub01_cidr_block
  - vcn01_subnet_pub01_display_name
  - vcn01_subnet_pub02_cidr_block
  - vcn01_subnet_app01_cidr_block
  - vcn02_subnet_pub01_cidr_block
  - vcn02_subnet_pub02_cidr_bloc
  - vcn02_subnet_db01_cidr_block
  - vcn02_display_name
  - vcn02_cidr_block
  - vcn02_dns_label
  - mysql_db_system_admin_username 

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment (Non Security Zone)"
    description: "Choose Compartment where you want to create the Virtual Machines."
  
  compartment_SZ_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment (Security Zone)"
    description: "Choose Security Zone Compartment where you want to create MySQL."

  region:
    type: oci:identity:region:name
    required: true
    title: Region
    description: "Choose Region where you want to deploy the resources defined by this stack."

  igw_display_name:
    type: string
    required: true
    title: "IGW Name"
    description: "Type Display name of the Internet Gateway from the VCN."

  vcn01_cidr_block:
    type: string
    required: true
    title: "Non Security Zone VCN CIDR Block"
    description: "Choose CIDR block that will be assigned to the Non Security Zone VCN."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_dns_label:
    type: string
    required: true
    title: "DNS Label of Non Security Zone VCN"
    description: "Type DNS label that will be asigned to the Non Security Zone VCN."

  vcn01_display_name:
    type: string
    required: true
    title: "Name of Non Security Zone VCN"
    description: "Type Display Name assigned to Non Security Zone VCN."

  vcn01_subnet_pub01_cidr_block:
    type: string
    required: true
    title: "Non Security Zone Public Subnet 1 CIDR Block"
    description: "Choose Non Security Zone CIDR block of Public Subnet 1."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_subnet_pub02_cidr_block:
    type: string
    required: true
    title: "Non Security Zone Public Subnet 2 CIDR Block"
    description: "Choose Non Security Zone CIDR block of Public Subnet 2"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_subnet_app01_cidr_block:
    type: string
    required: true
    title: "Non Security Zone App Subnet CIDR Block"
    description: "Choose Non Security Zone CIDR block of App Subnet"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  vcn02_cidr_block:
    type: string
    required: true
    title: "Security Zone VCN CIDR Block"
    description: "Choose CIDR block that will be assigned to the Security Zone VCN."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  vcn02_dns_label:
    type: string
    required: true
    title: "DNS Label of Security Zone VCN"
    description: "Type DNS label that will be asigned to the Security Zone VCN."

  vcn02_display_name:
    type: string
    required: true
    title: "Name of Security Zone VCN"
    description: "Type Display Name assigned to Security Zone VCN."

  vcn02_subnet_db01_cidr_block:
    type: string
    required: true
    title: "Security Zone Database Subnet CIDR Block"
    description: "Choose Security Zone CIDR block of Database Subnet"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  mysql_db_system_admin_username:
    type: string
    required: true
    title: "MySQL Admin User name"
    description: "Type MySQL Admin user name."

  mysql_db_system_admin_password:
    type: password
    required: true
    title: "MySQL Database Password"
    description: "Type MySQL atabase Password for ADMIN user."
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  BastionInstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Bastion Instance Shape"
    description: "Choose a shape allocated to Bastion instance."
    default: "VM.Standard.E2.1.Micro"
    dependsOn:
      compartmentId: ${compartment_ocid}

  WebserverInstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Webserver Instance Shape"
    description: "Choose a shape allocated to Webserver instance."
    default: "VM.Standard2.1"
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_os:
    type: enum
    title: "Image OS"
    description: "The OS/image installed on the Bastion instance."
    required: false
    enum:
      - "Oracle Linux - Latest Image"

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true